apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: eventarz-events
  name: eventarz-events
spec:
  replicas: 2
  selector:
    matchLabels:
      app: eventarz-events
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: eventarz-events
    spec:
      containers:
        - image: eventarzcontainerregistry.azurecr.io/eventarz-events:latest
          name: eventarz-events
          resources: {}
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: prod
status: {}
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: eventarz-events
  name: eventarz-events
spec:
  ports:
    - name: 8080-8080
      port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: eventarz-events
  type: ClusterIP
